"""Versioned common records for heterogeneous profiling results."""

from .artifact_integrity import (
    DETACHED_MANIFEST_NAME,
    DETACHED_VALIDATION_NAME,
    RECOVERY_RESULT_NAME,
    RECOVERY_ROOT_ID,
    ArtifactIntegrityError,
    build_detached_artifact_manifest,
    create_detached_recovery,
    validate_detached_artifact_manifest,
)
from .constants import CANONICAL_EVENT_NAMES, SCHEMA_MAJOR_VERSION, SCHEMA_VERSION
from .enums import (
    ArtifactKind,
    Availability,
    ClockType,
    DeviceType,
    EventType,
    MetricKind,
    MetricScope,
    Phase,
    ProfileMode,
    RecordType,
    RunMode,
    RunStatus,
    SyncMethod,
    ValueOrigin,
)
from .metric_catalog import METRIC_CATALOG, MetricDefinition
from .paths import RunPaths
from .records import (
    ArtifactReference,
    ClockDomain,
    ClockTransform,
    DeviceDescriptor,
    EventRecord,
    HostDescriptor,
    MetricSample,
    ModelDescriptor,
    RunManifest,
    SoftwareDescriptor,
    SyncPoint,
    WorkloadDescriptor,
)
from .serialization import (
    read_json,
    read_jsonl,
    record_from_dict,
    record_from_json,
    record_to_dict,
    record_to_json,
    write_json,
    write_jsonl,
)
from .validation import SchemaValidationError, validate_record, validate_record_dict

__all__ = [
    "ArtifactKind",
    "ArtifactIntegrityError",
    "ArtifactReference",
    "Availability",
    "CANONICAL_EVENT_NAMES",
    "ClockDomain",
    "ClockTransform",
    "ClockType",
    "DeviceDescriptor",
    "DeviceType",
    "DETACHED_MANIFEST_NAME",
    "DETACHED_VALIDATION_NAME",
    "EventRecord",
    "EventType",
    "HostDescriptor",
    "METRIC_CATALOG",
    "MetricDefinition",
    "MetricKind",
    "MetricSample",
    "MetricScope",
    "ModelDescriptor",
    "Phase",
    "ProfileMode",
    "RecordType",
    "RECOVERY_RESULT_NAME",
    "RECOVERY_ROOT_ID",
    "RunManifest",
    "RunMode",
    "RunPaths",
    "RunStatus",
    "SCHEMA_MAJOR_VERSION",
    "SCHEMA_VERSION",
    "SchemaValidationError",
    "SoftwareDescriptor",
    "SyncMethod",
    "SyncPoint",
    "ValueOrigin",
    "WorkloadDescriptor",
    "build_detached_artifact_manifest",
    "create_detached_recovery",
    "read_json",
    "read_jsonl",
    "record_from_dict",
    "record_from_json",
    "record_to_dict",
    "record_to_json",
    "validate_record",
    "validate_record_dict",
    "validate_detached_artifact_manifest",
    "write_json",
    "write_jsonl",
]
