"""Phase 4 hybrid source alignment and merge API."""

from .alignment import (
    AlignedTimestamp,
    AlignmentError,
    TimestampTransform,
    align_event,
    align_event_stream,
    align_metric,
    align_metric_stream,
    align_timestamp,
)
from .bundle import HybridBundleMerger, HybridMergeResult
from .clock_sync import (
    ClockEstimate,
    ClockProbeSample,
    ClockProbeTransport,
    ClockSyncError,
    FakeClockProbeTransport,
    LocalClockProbeTransport,
    collect_probe_samples,
    estimate_clock,
    probe_clock,
    same_clock_estimate,
)
from .config import AlignmentMethod, HybridMergeConfig, build_hybrid_plan
from .join import (
    ITERATION_MARKERS,
    JoinResult,
    MARKER_ORDER,
    MarkerValidation,
    OrderingIssue,
    join_requests,
    validate_marker_order,
    validate_marker_groups,
)
from .runtime_markers import (
    CANONICAL_MARKER_PHASES,
    RuntimeMarkerIngestError,
    ingest_runtime_marker_files,
)
from .runner import HybridRunResult, HybridRunner, build_hybrid_run_plan
from .runner_config import (
    PROFILE_MODES,
    HybridProfileMode,
    HybridRunnerConfig,
    HybridRunnerConfigError,
    load_hybrid_runner_config,
    validate_hybrid_invocation,
)
from .validation import (
    SourceBundle,
    SourceBundleError,
    classify_hybrid_status,
    load_source_bundle,
    validate_hybrid_records,
)

__all__ = [
    "AlignedTimestamp",
    "AlignmentError",
    "AlignmentMethod",
    "ClockEstimate",
    "ClockProbeSample",
    "ClockProbeTransport",
    "ClockSyncError",
    "FakeClockProbeTransport",
    "HybridBundleMerger",
    "HybridMergeConfig",
    "HybridMergeResult",
    "HybridProfileMode",
    "HybridRunResult",
    "HybridRunner",
    "HybridRunnerConfig",
    "HybridRunnerConfigError",
    "ITERATION_MARKERS",
    "JoinResult",
    "LocalClockProbeTransport",
    "MARKER_ORDER",
    "MarkerValidation",
    "OrderingIssue",
    "SourceBundle",
    "SourceBundleError",
    "TimestampTransform",
    "CANONICAL_MARKER_PHASES",
    "RuntimeMarkerIngestError",
    "PROFILE_MODES",
    "align_event",
    "align_event_stream",
    "align_metric",
    "align_metric_stream",
    "align_timestamp",
    "build_hybrid_plan",
    "build_hybrid_run_plan",
    "classify_hybrid_status",
    "collect_probe_samples",
    "estimate_clock",
    "ingest_runtime_marker_files",
    "join_requests",
    "load_source_bundle",
    "load_hybrid_runner_config",
    "probe_clock",
    "same_clock_estimate",
    "validate_hybrid_records",
    "validate_hybrid_invocation",
    "validate_marker_order",
    "validate_marker_groups",
]
